using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using StreetPetsData.Data;
using StreetPetsData.Models;
using StreetPetsData.Models.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StreetPetsData.Seed
{
    public static class Seeder
    {
        public static void ApplyMigrations(IServiceScopeFactory scopeFactory)
        {
            using (IServiceScope serviceScope = scopeFactory.CreateScope())
            {
                var dbContext = serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
                dbContext.Database.Migrate();
            }
        }

        public static async Task SeedBreeds(IServiceScopeFactory scopeFactory)
        {
            using (IServiceScope serviceScope = scopeFactory.CreateScope())
            {
                try
                {
                    var dbContext = serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

                    if (dbContext.Breeds.Any())
                    {
                        return;
                    }

                    var breeds = new List<Breed>()
                    {
                        new Breed { Name = "Mutt", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Caramel Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Afador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Affenhuahua", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Affenpinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Afghan Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Airedale Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akbash", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita Chow", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita Pit", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Alaskan Klee Kai", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Alaskan Malamute", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American English Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Eskimo Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Foxhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Hairless Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Leopard Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Pit Bull Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Pugabull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Staffordshire Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Water Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Anatolian Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Appenzeller Sennenhunde", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Auggie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Aussiedoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Aussiepom", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Cattle Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Kelpie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd Husky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd Lab Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd Pit Bull Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Stumpy Tail Cattle Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Azawakh", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Barbet", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basenji", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bassador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basset Fauve de Bretagne", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basset Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basset Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bavarian Mountain Scent Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Beabull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Beagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Beaglier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bearded Collie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bedlington Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Belgian Malinois", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Belgian Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Belgian Tervuren", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bergamasco Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Berger Picard", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bernedoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bernese Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bichon Frise", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Biewer Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Black and Tan Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Black Mouth Cur", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Black Russian Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bloodhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Blue Lacy", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bluetick Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bocker", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boerboel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boglen Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bohemian Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bolognese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Borador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Border Collie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Border Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Border Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bordoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Borzoi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "BoShih", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bossie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boston Boxer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boston Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boston Terrier Pekingese Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bouvier des Flandres", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxerdoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxmatian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxweiler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boykin Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bracco Italiano", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Braque du Bourbonnais", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Briard", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Brittany", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Broholmer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Brussels Griffon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bugg", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bull Arab", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bull-Pei", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bull Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullboxer Pit", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullmastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullmatian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cairn Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Canaan Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cane Corso", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cardigan Welsh Corgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Carolina Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Catahoula Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Catahoula Leopard Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Caucasian Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cav-a-Jack", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavachon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavalier King Charles Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Central Asian Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cesky Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chabrador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cheagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chesapeake Bay Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chi Chi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chi-Poo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chigi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chihuahua", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chilier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chinese Crested", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chinese Shar-Pei", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chinook", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chion", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chipin", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chiweenie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chorkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chow Chow", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chow Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chug", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chusky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cirneco dell’Etna", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Clumber Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cockalier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cockapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cocker Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Collie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Corgi Inu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Corgidor", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Corman Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Coton de Tulear", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Croatian Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Curly-Coated Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dachsador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dachshund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dalmatian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dandie Dinmont Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Daniff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Danish-Swedish Farmdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Deutscher Wachtelhund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doberdor", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doberman Pinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Docker", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dogo Argentino", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dogue de Bordeaux", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dorgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dorkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doxiepoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doxle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Drentsche Patrijshond", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Drever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dutch Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Cocker Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Foxhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Springer Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Toy Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Entlebucher Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Estrela Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Eurasier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Field Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Fila Brasileiro", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Finnish Lapphund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Finnish Spitz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Flat-Coated Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Fox Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "French Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "French Bullhuahua", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "French Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Frenchton", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Frengle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Longhaired Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Pinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shepherd Pit Bull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shepherd Rottweiler Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Sheprador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shorthaired Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Spitz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Wirehaired Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Giant Schnauzer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Glen of Imaal Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Goberian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Goldador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Cocker Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Retriever Corgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Goldendoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Gollie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Gordon Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Great Dane", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Great Pyrenees", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Greater Swiss Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Greyador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Greyhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hamiltonstovare", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hanoverian Scenthound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Harrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Havanese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hokkaido", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Horgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hovawart", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Huskita", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Huskydoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Ibizan Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Icelandic Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Red And White Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Water Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Wolfhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Italian Greyhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jack-A-Poo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jack Chi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jack Russell Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jackshund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Japanese Chin", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Japanese Spitz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Korean Jindo Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kai Ken", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Karelian Bear Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Keeshond", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kerry Blue Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "King Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kishu Ken", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Komondor", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kooikerhondje", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kuvasz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kyi-Leo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lab Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labernese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labmaraner", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labrabull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labradane", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labradoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labrador Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labrastaff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lagotto Romagnolo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lakeland Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lancashire Heeler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Leonberger", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lhasa Apso", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lhasapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lowchen", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maltese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maltese Shih Tzu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maltipoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Manchester Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maremma Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mastador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Miniature Pinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Miniature Schnauzer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Morkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mountain Cur", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mudi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mutt (Mixed)", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Neapolitan Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Newfoundland", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norfolk Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Northern Inuit Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwegian Buhund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwegian Elkhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwegian Lundehund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwich Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Nova Scotia Duck Tolling Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Old English Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Otterhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Papillon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Papipoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Patterdale Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Peekapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pekingese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pembroke Welsh Corgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Petit Basset Griffon Vendéen", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pharaoh Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pitsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Plott", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pocket Beagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Polish Lowland Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomchi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomeagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomeranian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Poochon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Poodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Podengo Pequeno", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Water Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pug", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pugalier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Puggle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Puginese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Puli", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pyredoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pyrenean Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pyrenean Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rat Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Redbone Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rhodesian Ridgeback", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rottador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rottle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rottweiler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Saint Berdoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Saint Bernard", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Saluki", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Samoyed", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Samusky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Schipperke", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Schnoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Scottish Deerhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Scottish Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sealyham Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sheepadoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shepsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shetland Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shiba Inu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shichon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shih-Poo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shih Tzu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shiloh Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shiranian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shollie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shorkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Siberian Husky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Silken Windhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Silky Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Skye Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sloughi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Small Munsterlander Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Soft Coated Wheaten Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Spanish Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Spinone Italiano", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Springador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Stabyhoun", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Staffordshire Bull Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Staffy Bull Bullmastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Standard Schnauzer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sussex Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Swedish Lapphund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Swedish Vallhund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Taiwan Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Terripoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Texas Heeler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Tibetan Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Tibetan Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Tibetan Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Toy Fox Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Transylvanian Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Treeing Tennessee Brindle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Treeing Walker Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Valley Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Vizsla", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Weimaraner", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Welsh Springer Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Welsh Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "West Highland White Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Westiepoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Whippet", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Whoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Wirehaired Pointing Griffon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Xoloitzcuintli", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Yorkipoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Yorkshire Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Afador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Affenhuahua", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Affenpinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Afghan Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Airedale Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akbash", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita Chow", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita Pit", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Akita Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Alaskan Klee Kai", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Alaskan Malamute", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American English Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Eskimo Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Foxhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Hairless Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Leopard Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Pit Bull Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Pugabull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Staffordshire Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "American Water Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Anatolian Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Appenzeller Sennenhunde", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Auggie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Aussiedoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Aussiepom", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Cattle Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Kelpie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd Husky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd Lab Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Shepherd Pit Bull Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Stumpy Tail Cattle Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Australian Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Azawakh", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Barbet", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basenji", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bassador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basset Fauve de Bretagne", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basset Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Basset Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bavarian Mountain Scent Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Beabull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Beagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Beaglier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bearded Collie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bedlington Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Belgian Malinois", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Belgian Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Belgian Tervuren", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bergamasco Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Berger Picard", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bernedoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bernese Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bichon Frise", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Biewer Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Black and Tan Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Black Mouth Cur", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Black Russian Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bloodhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Blue Lacy", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bluetick Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bocker", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boerboel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boglen Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bohemian Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bolognese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Borador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Border Collie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Border Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Border Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bordoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Borzoi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "BoShih", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bossie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boston Boxer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boston Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boston Terrier Pekingese Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bouvier des Flandres", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxerdoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxmatian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boxweiler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Boykin Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bracco Italiano", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Braque du Bourbonnais", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Briard", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Brittany", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Broholmer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Brussels Griffon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bugg", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bull Arab", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bull-Pei", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bull Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullboxer Pit", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullmastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Bullmatian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cairn Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Canaan Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cane Corso", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cardigan Welsh Corgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Carolina Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Catahoula Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Catahoula Leopard Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Caucasian Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cav-a-Jack", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavachon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavalier King Charles Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cavapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Central Asian Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cesky Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chabrador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cheagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chesapeake Bay Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chi Chi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chi-Poo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chigi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chihuahua", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chilier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chinese Crested", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chinese Shar-Pei", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chinook", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chion", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chipin", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chiweenie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chorkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chow Chow", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chow Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chug", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Chusky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cirneco dell’Etna", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Clumber Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cockalier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cockapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Cocker Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Collie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Corgi Inu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Corgidor", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Corman Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Coton de Tulear", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Croatian Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Curly-Coated Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dachsador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dachshund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dalmatian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dandie Dinmont Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Daniff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Danish-Swedish Farmdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Deutscher Wachtelhund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doberdor", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doberman Pinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Docker", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dogo Argentino", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dogue de Bordeaux", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dorgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dorkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doxiepoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Doxle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Drentsche Patrijshond", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Drever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Dutch Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Cocker Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Foxhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Springer Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "English Toy Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Entlebucher Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Estrela Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Eurasier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Field Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Fila Brasileiro", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Finnish Lapphund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Finnish Spitz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Flat-Coated Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Fox Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "French Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "French Bullhuahua", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "French Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Frenchton", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Frengle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Longhaired Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Pinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shepherd Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shepherd Pit Bull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shepherd Rottweiler Mix", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Sheprador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Shorthaired Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Spitz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "German Wirehaired Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Giant Schnauzer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Glen of Imaal Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Goberian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Goldador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Cocker Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Retriever Corgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Golden Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Goldendoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Gollie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Gordon Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Great Dane", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Great Pyrenees", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Greater Swiss Mountain Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Greyador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Greyhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hamiltonstovare", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hanoverian Scenthound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Harrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Havanese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hokkaido", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Horgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Hovawart", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Huskita", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Huskydoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Ibizan Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Icelandic Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Red And White Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Setter", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Water Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Irish Wolfhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Italian Greyhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jack-A-Poo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jack Chi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jack Russell Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Jackshund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Japanese Chin", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Japanese Spitz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Korean Jindo Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kai Ken", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Karelian Bear Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Keeshond", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kerry Blue Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "King Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kishu Ken", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Komondor", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kooikerhondje", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kuvasz", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Kyi-Leo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lab Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labernese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labmaraner", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labrabull", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labradane", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labradoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labrador Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labrastaff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Labsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lagotto Romagnolo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lakeland Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lancashire Heeler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Leonberger", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lhasa Apso", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lhasapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Lowchen", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maltese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maltese Shih Tzu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maltipoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Manchester Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Maremma Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mastador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Miniature Pinscher", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Miniature Schnauzer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Morkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mountain Cur", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mudi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Mutt (Mixed)", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Neapolitan Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Newfoundland", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norfolk Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Northern Inuit Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwegian Buhund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwegian Elkhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwegian Lundehund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Norwich Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Nova Scotia Duck Tolling Retriever", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Old English Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Otterhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Papillon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Papipoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Patterdale Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Peekapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pekingese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pembroke Welsh Corgi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Petit Basset Griffon Vendéen", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pharaoh Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pitsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Plott", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pocket Beagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Polish Lowland Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomapoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomchi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomeagle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomeranian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pomsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Poochon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Poodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Podengo Pequeno", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Portuguese Water Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pug", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pugalier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Puggle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Puginese", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Puli", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pyredoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pyrenean Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Pyrenean Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rat Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Redbone Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rhodesian Ridgeback", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rottador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rottle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Rottweiler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Saint Berdoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Saint Bernard", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Saluki", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Samoyed", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Samusky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Schipperke", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Schnoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Scottish Deerhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Scottish Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sealyham Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sheepadoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shepsky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shetland Sheepdog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shiba Inu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shichon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shih-Poo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shih Tzu", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shiloh Shepherd", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shiranian", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shollie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Shorkie", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Siberian Husky", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Silken Windhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Silky Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Skye Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sloughi", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Small Munsterlander Pointer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Soft Coated Wheaten Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Spanish Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Spinone Italiano", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Springador", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Stabyhoun", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Staffordshire Bull Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Staffy Bull Bullmastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Standard Schnauzer", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Sussex Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Swedish Lapphund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Swedish Vallhund", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Taiwan Dog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Terripoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Texas Heeler", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Tibetan Mastiff", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Tibetan Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Tibetan Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Toy Fox Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Transylvanian Hound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Treeing Tennessee Brindle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Treeing Walker Coonhound", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Valley Bulldog", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Vizsla", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Weimaraner", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Welsh Springer Spaniel", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Welsh Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "West Highland White Terrier", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Westiepoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Whippet", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Whoodle", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Wirehaired Pointing Griffon", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Xoloitzcuintli", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Yorkipoo", EntityStatus = EntityStatus.ACTIVE },
                        new Breed { Name = "Yorkshire Terrier", EntityStatus = EntityStatus.ACTIVE },
                    };

                    await dbContext.Breeds.AddRangeAsync(breeds);
                    await dbContext.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    throw;
                }
            }
        }
    }
}